### ISSUE TITLE
Want to navigate to next component from the button which is in the dashboard container not in header,sidebar & footer.

### ISSUE THREAD

**Issue by deepaknouliya** [start-angular/SB-Admin-BS4-Angular-5#162] opened 2017-11-03 11:15 UTC
Want to navigate to next component from the button which is in the dashboard container not in header,sidebar & footer.

**Comment by alpesh-patel93** [comment] 2017-12-15 12:30
The issue is not clear. You can use `[routerLink]="['/path']"` in button tag to navigate to any route, Thanks.

**Comment by alpesh-patel93** [comment] 2017-12-20 06:39
Closing this for now, Please reopen the issue with explanation if you find any problem.

**Closed by alpesh-patel93** 2017-12-20 06:39 UTC
